---
  - name: install python mysql bindings
    apt: name=python-mysqldb state=latest
    become: yes
    become_method: sudo

  - name: 'Install MySQL Server'
    apt: name={{ item }} state=latest
    with_items:
        - mysql-server
        - mysql-client
        - python-dev

  - name: Update MySQL root password for all root accounts
    mysql_user: name=root host={{ item }} password={{ mysql_root_pass }} state=present
    with_items:
     - "{{ ansible_hostname }}"
     - 127.0.0.1
     - ::1
     - localhost

  - name: Copy the root credentials as .my.cnf file
    template: src=root.cnf.j2 dest=~/.my.cnf mode=0600

  - name: Ensure Anonymous user(s) are not in the database
    mysql_user: name='' host={{ item }} state=absent
    with_items:
     - localhost
     - "{{ ansible_hostname }}"

  - name: 'Create database user'
    mysql_user:
     name: db_user
     password: Passw0rd
     priv: '*.*:ALL'
     state: present
     host: '%'

  - name: 'Create application database'
    mysql_db:
       name: employee_db
       state: present
       login_user: db_user
       login_password: Passw0rd

  - debug : var=mysql_root_pass

  - name: Remove the test database
    mysql_db: name=test state=absent
    notify:
     - Restart MySQL